### ISSUE TITLE
load_collection(SENTINEL2_L2A) doesn't work with non-lonlat bbox

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#143] opened 2022-10-11 13:49 UTC
reported at https://discuss.eodc.eu/t/spatial-extent-different-srs/484

```python
cube =  con.load_collection(
    "SENTINEL2_L2A",
    # "TERRASCOPE_S2_TOC_V2",
    # "SENTINEL2_L2A_SENTINELHUB",
    # spatial_extent={"west": 2.15, "south": 42.15, "east": 2.4, "north": 42.4},
    spatial_extent = {
        "west": 429770, "east": 433953, "south": 4666780, "north": 4672292, 
        "crs": "epsg:32631",
    },
    temporal_extent=["2019-01-01", "2019-01-10"],
    bands=["B04"],
)
```

gives 
```
OpenEoApiError: [500] Internal: Failed to process synchronously on backend vito: 
OpenEoApiError("[500] Internal: Server error: 
HTTPError('400 Client Error:  for url: 
https://services.terrascope.be/catalogue/products?collection=urn%3Aeop%3AVITO%3ATERRASCOPE_S2_TOC_V2&bbox=429770%2C4666780%2C433953%2C4672292&sortKeys=title&startIndex=1&start=2019-01-01T00%3A00%3A00&end=2019-01-10T23%3A59%3A59.999999&cloudCover=%5B0%2C100.0%5D') (ref: r-50f31a0b12ba4a2b919ba661c6f5da4b)") (ref: r-764629bc773f4c25bdbaebaa95708ed0)
```

apparently our tile availability check does not support non-lonlat bboxes yet

**Comment by jdries** [comment] 2023-01-26 15:00
This one got fixed in the meantime, at least can't reproduce with this code.

**Closed by jdries** 2023-01-26 15:00 UTC
