### ISSUE TITLE
CORS: Access-Control-Expose-Headers not present in non-OPTION responses

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-driver#54] opened 2020-11-17 12:49 UTC
The Access-Control-Expose-Headers is not present in non-OPTION (e.g. POST) responses and thus the JS client can't access OpenEO-Identifier etc. 

API spec: https://open-eo.github.io/openeo-api/draft/index.html#section/Cross-Origin-Resource-Sharing-(CORS)/CORS-headers

Original issue: https://github.com/Open-EO/openeo-web-editor/issues/123

You implement to return the header in Options, so I hope it's an easy fix.

**Comment by soxofaan** [comment] 2020-11-17 14:10
on what endpoint is that?

any chance this is duplicate of #51 ?

**Comment by m-mohr** [comment] 2020-11-17 14:33
No, not a duplicate.

For me it was POST /jobs, may also apply to POST /services and/or other endpoints.

**Closed** 2020-11-30 15:33 UTC
Labels: bug

**Comment by soxofaan** [comment] 2020-11-30 15:35
should be fixed with next prod deploy of VITO backend (somewhere this week)
