### ISSUE TITLE
creating, changing and saving jobs on VITO backend doesn't work

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-python-driver#55] opened 2020-11-18 17:22 UTC
There seems to be a problem with the creation and the change of jobs on the VITO backend (via online editor). I am not able to save process graphs as new batch jobs or to change existing jobs (404 error). This seems to be a new or recurring issue since I was still able to do so just a week ago. 

Job creation/change on another backend still works in the editor (GEE tested). Also, upon starting a job via R-client it is successfully registered on the backend (VITO).

On a second note, giving titles to jobs never seemed to work for me, no matter what client was used.

Please let me know if I should move this to another repository.

**Comment by soxofaan** [comment] 2020-11-19 09:07
I think this is caused by #54 : js client can not extract "openeo-identifier" from `/jobs` POST response because of CORS issues.
The batch job should be stored however, so if you reload the online editor, it should be listed under batch jobs. can you confirm?

About the other issue: we indeed don't store or return the job's title yet. I'll have a look if that can be resolved easily

**Comment by jonathom** [comment] 2020-11-19 10:53
yes, the job is indeed saved and visible upon reloading. Thank you.

However job edits and changes are not stored even upon reloading.

**Comment by soxofaan** [comment] 2020-11-19 11:05
thanks for confirming

indeed, the VITO backend currently does not support modifying batch jobs -> #56 
the error message shows this:
![Screenshot from 2020-11-19 11-57-50](https://user-images.githubusercontent.com/44946/99658082-4b637100-2a5f-11eb-91ea-f2004bdbd3fc.png)

@m-mohr  would it be easy to disable the "save" button when backend does not support updates?

**Comment by m-mohr** [comment] 2020-11-19 11:34
I'll check: https://github.com/Open-EO/openeo-web-editor/issues/128

**Comment by m-mohr** [comment] 2020-11-19 16:01
@soxofaan Your suggestion has been implemented and released as v0.5.2, can now be tested at https://editor.openeo.org/

**Comment by soxofaan** [comment] 2020-11-30 15:36
CORS issue (#54) should be fixed with next prod deploy of VITO backend (somewhere this week probably)

**Comment by soxofaan** [comment] 2021-11-03 13:34
I think this can be closed
#56 is follow up issue

**Closed by soxofaan** 2021-11-03 13:34 UTC
